// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e7f8a0b-b2d2-497b-89e2-9b971e09d71d"),
                            Name = "Яблоко"
                        },
                        new
                        {
                            Id = new Guid("c8291708-5ece-4f60-95f7-1366561c12a8"),
                            Name = "Яблочный пирог"
                        },
                        new
                        {
                            Id = new Guid("6ed0138a-7ef3-4e84-8adb-0fd001466f03"),
                            Name = "Яблочное варенье"
                        },
                        new
                        {
                            Id = new Guid("fe36cdf9-322d-46fe-8396-fa6e0dab6d98"),
                            Name = "Яблочный суп"
                        },
                        new
                        {
                            Id = new Guid("a1f87413-0fb7-47c8-8859-d51a5d7feb3c"),
                            Name = "что-то с яблоком"
                        },
                        new
                        {
                            Id = new Guid("2b307bc9-8727-4365-9fef-a2d035b8449d"),
                            Name = "Пирожок с яблоком"
                        },
                        new
                        {
                            Id = new Guid("0118c7f2-8d26-4df6-b776-1a3638031a68"),
                            Name = "Груша"
                        },
                        new
                        {
                            Id = new Guid("5c87ceea-0e76-414b-9475-31d03f57abff"),
                            Name = "Грушевый торт"
                        },
                        new
                        {
                            Id = new Guid("cc18355d-4f24-4dcc-9340-d36d0609d4e9"),
                            Name = "Варенье с грушей"
                        },
                        new
                        {
                            Id = new Guid("0c7d59c3-3bd5-432a-8732-d9e6b3023334"),
                            Name = "Ароматизатор - Груша"
                        },
                        new
                        {
                            Id = new Guid("c0bf3521-226d-4b50-9c48-1a8b85c127f3"),
                            Name = "Игрушка - груша"
                        },
                        new
                        {
                            Id = new Guid("a10505b5-0737-496c-89f4-a6f1d8c8fec4"),
                            Name = "Книга рецептов - Груши, Яблоки"
                        },
                        new
                        {
                            Id = new Guid("0c6434f3-4702-4c6b-a777-3c8cbaf93058"),
                            Name = "бебра"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
